import * as stylex from "@stylexjs/stylex";

const modernCallFadeIn = stylex.keyframes({
 from: {
  opacity: 0,
 },
 to: {
  opacity: 1,
 },
});

const slideDownFade = stylex.keyframes({
 from: {
  opacity: 0,
  transform: "translateY(-20px)",
 },
 to: {
  opacity: 1,
  transform: "translateY(0)",
 },
});

const modernPulse = stylex.keyframes({
 "0%": {
  transform: "translate(-50%, -50%) scale(1)",
  opacity: 1,
 },
 "100%": {
  transform: "translate(-50%, -50%) scale(1.4)",
  opacity: 0,
 },
});

const overlayFadeIn = stylex.keyframes({
 from: {
  opacity: 0,
 },
 to: {
  opacity: 1,
 },
});

const callSlideUp = stylex.keyframes({
 from: {
  opacity: 0,
  transform: "translateY(50px) scale(0.9)",
 },
 to: {
  opacity: 1,
  transform: "translateY(0) scale(1)",
 },
});

const audioWave = stylex.keyframes({
 "0%": {
  transform: "translateX(-100%)",
 },
 "100%": {
  transform: "translateX(-100%)",
 },
 "50%": {
  transform: "translateX(200%)",
 },
});

const slideInFromRight = stylex.keyframes({
 from: {
  opacity: 0,
  transform: "translateX(100%)",
 },
 to: {
  opacity: 1,
  transform: "translateX(0)",
 },
});

export const GeneralCallsStyles = stylex.create(
 {
  callOverlay: {
   position: "fixed",
   top: "0",
   left: "0",
   right: "0",
   bottom: "0",
   background: "rgba(0, 0, 0, 0.95)",
   backdropFilter: "blur(10px)",
   zIndex: 9999,
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   animationName: overlayFadeIn,
   animationDuration: "0.3s",
   animationTimingFunction: "ease",
   animationFillMode: "forwards",
  },
  modernCallOverlay: {
   position: "fixed",
   top: "0",
   left: "0",
   right: "0",
   bottom: "0",
   background: "#000",
   zIndex: 9999,
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   animationName: modernCallFadeIn,
   animationDuration: "0.4s",
   animationTimingFunction: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
  },
  modernActiveCall: {
   width: "100%",
   height: "100%",
   position: "relative",
   display: "flex",
   flexDirection: "column",
   background: "#000",
   overflow: "hidden",
  },
  modernCallHeader: {
   position: "absolute",
   top: "0",
   left: "0",
   right: "0",
   padding: "24px 32px",
   background:
    "linear-gradient(180deg, rgba(0, 0, 0, 0.8) 0%, rgba(0, 0, 0, 0) 100%)",
   display: "flex",
   alignItems: "center",
   justifyContent: "space-between",
   zIndex: 100,
   opacity: 1,
   transform: "translateY(0)",
   transition: "opacity 0.3s ease, transform 0.3s ease",
  },
  modernCallHeaderHidden: {
   opacity: 0,
   transform: "translateY(-20px)",
   pointerEvents: "none",
  },
  modernCallInfo: {
   display: "flex",
   alignItems: "center",
   gap: "16px",
  },
  modernCallAvatar: {
   width: "48px",
   height: "48px",
   borderRadius: "50%",
   border: "2px solid rgba(255, 255, 255, 0.3)",
   objectFit: "cover",
  },
  modernCallUserH3: {
   fontSize: "18px",
   fontWeight: 600,
   color: "white",
   margin: "0 0 4px 0",
   textShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
   "@media (max-width: 768px)": {
    fontSize: "16px",
   },
  },
  modernCallUserP: {
   fontSize: "14px",
   color: "rgba(255, 255, 255, 0.8)",
   margin: "0",
   textShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
   "@media (max-width: 768px)": {
    fontSize: "13px",
   },
  },
  modernMinimizeBtn: {
   width: "44px",
   height: "44px",
   borderRadius: "50%",
   border: "none",
   background: "rgba(255, 255, 255, 0.15)",
   backdropFilter: "blur(10px)",
   color: "white",
   fontSize: "16px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   transition: "all 0.2s ease",
  },
  modernMinimizeBtnHover: {
   ":hover": {
    background: "rgba(255, 255, 255, 0.25)",
    transform: "scale(1.1)",
   },
  },
  modernMinimizeBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernMinimizeBtnModernMinimizeMobileVisible: {
   "@media (max-width: 768px)": {
    display: "flex",
    width: "40px",
    height: "40px",
    fontSize: "14px",
   },
  },
  modernVideoContainer: {
   width: "100%",
   height: "100%",
   position: "relative",
   background: "#000",
  },
  modernRemoteVideo: {
   width: "100%",
   height: "100%",
   objectFit: "cover",
   background: "#000",
  },
  modernLocalVideo: {
   position: "absolute",
   top: "80px",
   right: "24px",
   width: "240px",
   height: "180px",
   borderRadius: "16px",
   objectFit: "cover",
   border: "3px solid rgba(255, 255, 255, 0.3)",
   background: "#1a1a1a",
   zIndex: 50,
   boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
   transform: "scaleX(-1)",
   transition: "top 0.3s ease, border-color 0.2s ease, box-shadow 0.2s ease",
   "@media (max-width: 768px)": {
    width: "120px",
    height: "160px",
    top: "70px",
    right: "16px",
    borderRadius: "12px",
    borderWidth: "2px",
   },
  },
  modernLocalVideoHover: {
   ":hover": {
    borderColor: "rgba(255, 255, 255, 0.5)",
    boxShadow: "0 12px 40px rgba(0, 0, 0, 0.6)",
   },
  },
  modernLocalVideoUiHidden: {
   top: "20px",
   "@media (max-width: 768px)": {
    top: "16px",
   },
  },
  modernAudioCallUi: {
   flex: "1",
   display: "flex",
   flexDirection: "column",
   alignItems: "center",
   justifyContent: "center",
   background: "linear-gradient(135deg, #1a1a1a 0%, #000 100%)",
   padding: "40px",
   textAlign: "center",
  },
  modernAudioAvatarWrapper: {
   position: "relative",
   marginBottom: "40px",
  },
  modernAudioAvatar: {
   width: "180px",
   height: "180px",
   borderRadius: "50%",
   border: "4px solid rgba(255, 152, 0, 0.3)",
   objectFit: "cover",
   position: "relative",
   zIndex: 2,
   boxShadow: "0 12px 48px rgba(0, 0, 0, 0.4)",
   "@media (max-width: 768px)": {
    width: "140px",
    height: "140px",
    borderWidth: "3px",
   },
  },
  modernAudioPulse: {
   position: "absolute",
   top: "50%",
   left: "50%",
   transform: "translate(-50%, -50%)",
   width: "180px",
   height: "180px",
   borderRadius: "50%",
   border: "3px solid rgba(255, 152, 0, 0.4)",
   animationName: modernPulse,
   animationDuration: "2s",
   animationTimingFunction: "ease-in-out",
   animationIterationCount: "infinite",
   "@media (max-width: 768px)": {
    width: "140px",
    height: "140px",
    borderWidth: "2px",
   },
  },
  modernAudioCallUiH3: {
   fontSize: "32px",
   fontWeight: 600,
   color: "white",
   margin: "0 0 12px 0",
   "@media (max-width: 768px)": {
    fontSize: "26px",
   },
  },
  modernAudioCallUiP: {
   fontSize: "18px",
   color: "rgba(255, 255, 255, 0.7)",
   margin: "0",
   "@media (max-width: 768px)": {
    fontSize: "16px",
   },
  },
  modernCallControlsWrapper: {
   position: "absolute",
   bottom: "0",
   left: "0",
   right: "0",
   padding: "32px",
   background:
    "linear-gradient(0deg, rgba(0, 0, 0, 0.8) 0%, rgba(0, 0, 0, 0) 100%)",
   display: "flex",
   justifyContent: "center",
   zIndex: 100,
   opacity: 1,
   transform: "translateY(0)",
   transition: "opacity 0.3s ease, transform 0.3s ease",
   "@media (max-width: 768px)": {
    padding: "24px 16px",
   },
  },
  modernCallControlsWrapperHidden: {
   opacity: 0,
   transform: "translateY(20px)",
   pointerEvents: "none",
  },
  modernCallControls: {
   display: "flex",
   gap: "20px",
   alignItems: "center",
   "@media (max-width: 768px)": {
    gap: "16px",
   },
  },
  modernControlBtn: {
   width: "56px",
   height: "56px",
   borderRadius: "50%",
   border: "none",
   background: "rgba(255, 255, 255, 0.15)",
   backdropFilter: "blur(10px)",
   color: "white",
   fontSize: "20px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   transition: "all 0.2s ease",
   position: "relative",
   "@media (max-width: 768px)": {
    width: "52px",
    height: "52px",
    fontSize: "18px",
   },
  },
  modernControlBtnHover: {
   ":hover": {
    background: "rgba(255, 255, 255, 0.25)",
    transform: "scale(1.1)",
   },
  },
  modernControlBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernEndCallBtn: {
   width: "64px",
   height: "64px",
   borderRadius: "50%",
   border: "none",
   background: "#ff4757",
   color: "white",
   fontSize: "24px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   transition: "all 0.2s ease",
   boxShadow: "0 4px 16px rgba(255, 71, 87, 0.4)",
   "@media (max-width: 768px)": {
    width: "60px",
    height: "60px",
    fontSize: "22px",
   },
  },
  modernEndCallBtnHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.1)",
    boxShadow: "0 6px 24px rgba(255, 71, 87, 0.6)",
   },
  },
  modernEndCallBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernEndCallBtnI: {
   transform: "rotate(135deg)",
  },
  modernCallHeaderMaxWidth768px: {
   "@media (max-width: 768px)": {
    padding: "20px 16px",
   },
  },
  modernCallAvatarMaxWidth768px: {
   "@media (max-width: 768px)": {
    width: "40px",
    height: "40px",
   },
  },
  incomingCall: {
   background: "var(--bg-secondary)",
   borderRadius: "24px",
   padding: "40px",
   textAlign: "center",
   maxWidth: "400px",
   width: "90%",
   boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
   animationName: callSlideUp,
   animationDuration: "0.4s",
   animationTimingFunction: "ease",
   animationFillMode: "forwards",
   "@media (max-width: 768px)": {
    padding: "30px 20px",
    borderRadius: "16px",
   },
  },
  incomingCallImg: {
   width: "120px",
   height: "120px",
   borderRadius: "50%",
   border: "4px solid var(--border)",
   marginBottom: "20px",
   objectFit: "cover",
   "@media (max-width: 768px)": {
    width: "100px",
    height: "100px",
   },
  },
  incomingCallH3: {
   fontSize: "24px",
   fontWeight: 600,
   color: "var(--text-primary)",
   marginBottom: "8px",
   "@media (max-width: 768px)": {
    fontSize: "22px",
   },
  },
  incomingCallP: {
   fontSize: "16px",
   color: "var(--text-secondary)",
   marginBottom: "30px",
  },
  callActions: {
   display: "flex",
   gap: "20px",
   justifyContent: "center",
   "@media (max-width: 768px)": {
    gap: "30px",
   },
  },
  declineBtn: {
   width: "70px",
   height: "70px",
   border: "none",
   borderRadius: "50%",
   fontSize: "24px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   transition: "all 0.2s ease",
   background: "#ff4757",
   color: "white",
   "@media (max-width: 768px)": {
    width: "80px",
    height: "80px",
    fontSize: "28px",
   },
  },
  acceptBtn: {
   width: "70px",
   height: "70px",
   border: "none",
   borderRadius: "50%",
   fontSize: "24px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   transition: "all 0.2s ease",
   background: "#2ed573",
   color: "white",
   "@media (max-width: 768px)": {
    width: "80px",
    height: "80px",
    fontSize: "28px",
   },
  },
  declineBtnHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.1)",
   },
  },
  declineBtnBefore: {
   "::before": {
    content: "\"\uf095\"",
    fontFamily: "Font Awesome 6 Free",
    fontWeight: 900,
    transform: "rotate(135deg)",
   },
  },
  acceptBtnHover: {
   ":hover": {
    background: "#26d063",
    transform: "scale(1.1)",
   },
  },
  acceptBtnBefore: {
   "::before": {
    content: "\"\uf095\"",
    fontFamily: "Font Awesome 6 Free",
    fontWeight: 900,
   },
  },
  activeCall: {
   width: "100%",
   height: "100%",
   position: "relative",
   display: "flex",
   flexDirection: "column",
   background: "#000",
  },
  videoContainer: {
   flex: "1",
   position: "relative",
   overflow: "hidden",
   background: "#000",
  },
  remoteVideo: {
   width: "100%",
   height: "100%",
   objectFit: "cover",
   background: "#000",
  },
  localVideo: {
   position: "absolute",
   width: "200px",
   height: "150px",
   objectFit: "cover",
   background: "#333",
   zIndex: 10,
   "@media (max-width: 768px)": {
    width: "120px",
    height: "160px",
    top: "20px",
    right: "15px",
   },
  },
  callStatusOverlay: {
   position: "absolute",
   top: "20px",
   left: "20px",
   background: "rgba(0, 0, 0, 0.6)",
   backdropFilter: "blur(10px)",
   padding: "12px 20px",
   borderRadius: "25px",
   zIndex: 15,
   border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  callStatusOverlayH3: {
   fontSize: "16px",
   fontWeight: 500,
   color: "white",
   margin: "0",
  },
  audioCallUi: {
   flex: "1",
   display: "flex",
   flexDirection: "column",
   alignItems: "center",
   justifyContent: "center",
   background: "var(--bg-secondary)",
   color: "var(--text-primary)",
   textAlign: "center",
  },
  audioCallUiImg: {
   width: "160px",
   height: "160px",
   borderRadius: "50%",
   border: "4px solid rgba(255, 255, 255, 0.3)",
   marginBottom: "30px",
   objectFit: "cover",
   "@media (max-width: 768px)": {
    width: "140px",
    height: "140px",
    marginBottom: "20px",
   },
  },
  audioCallUiH3: {
   fontSize: "28px",
   fontWeight: 600,
   marginBottom: "8px",
   "@media (max-width: 768px)": {
    fontSize: "24px",
   },
  },
  audioCallUiP: {
   fontSize: "18px",
   opacity: 0.8,
   "@media (max-width: 768px)": {
    fontSize: "16px",
   },
  },
  callControls: {
   position: "absolute",
   bottom: "40px",
   left: "50%",
   transform: "translateX(-50%)",
   display: "flex",
   gap: "20px",
   zIndex: 15,
   "@media (max-width: 768px)": {
    bottom: "30px",
   },
  },
  endCallBtn: {
   width: "70px",
   height: "70px",
   border: "none",
   borderRadius: "50%",
   background: "#ff4757",
   color: "white",
   fontSize: "24px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   transition: "all 0.2s ease",
   "@media (max-width: 768px)": {
    width: "80px",
    height: "80px",
    fontSize: "28px",
   },
  },
  endCallBtnHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.1)",
   },
  },
  endCallBtnBefore: {
   "::before": {
    content: "\"\uf095\"",
    fontFamily: "Font Awesome 6 Free",
    fontWeight: 900,
    transform: "rotate(135deg)",
   },
  },
  callButtons: {
   display: "flex",
   gap: "12px",
   marginLeft: "auto",
   "@media (max-width: 768px)": {
    gap: "10px",
    marginRight: "-5px",
   },
  },
  callBtn: {
   width: "44px",
   height: "44px",
   border: "1px solid var(--border)",
   background: "var(--bg-tertiary)",
   color: "var(--text-primary)",
   borderRadius: "50%",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   fontSize: "18px",
   transition: "all 0.2s ease",
   position: "relative",
   "@media (max-width: 768px)": {
    width: "42px",
    height: "42px",
    fontSize: "17px",
    background: "transparent",
    border: "none",
    color: "#ffa500",
   },
  },
  callBtnHoverNotDisabled: {
   ":hover:not(:disabled)": {
    background: "var(--button-primary)",
    color: "white",
    transform: "scale(1.1)",
   },
   "@media (max-width: 768px)": {
    ":hover:not(:disabled)": {
     background: "rgba(128, 128, 128, 0.3)",
     color: "#ffa500",
     transform: "none",
    },
   },
  },
  callBtnDisabled: {
   ":disabled": {
    opacity: 0.5,
    cursor: "not-allowed",
    transform: "none",
   },
  },
  audioCallBefore: {
   "::before": {
    content: "\"\uf095\"",
    fontFamily: "Font Awesome 6 Free",
    fontWeight: 900,
   },
  },
  videoCallBefore: {
   "::before": {
    content: "\"\uf03d\"",
    fontFamily: "Font Awesome 6 Free",
    fontWeight: 900,
    display: "none",
   },
  },
  callBtnActiveNotDisabled: {
   "@media (max-width: 768px)": {
    ":active:not(:disabled)": {
     background: "rgba(128, 128, 128, 0.5)",
     transform: "scale(0.95)",
    },
   },
  },
  activeCallStatus: {
   position: "absolute",
   top: "30px",
   left: "50%",
   transform: "translateX(-50%)",
   textAlign: "center",
   background: "rgba(0, 0, 0, 0.75)",
   backdropFilter: "blur(10px)",
   padding: "16px 32px",
   borderRadius: "12px",
   zIndex: 20,
   border: "1px solid rgba(255, 255, 255, 0.15)",
  },
  activeCallStatusH3: {
   fontSize: "18px",
   fontWeight: 600,
   color: "white",
   marginBottom: "4px",
   letterSpacing: "0.3px",
  },
  activeCallStatusP: {
   fontSize: "14px",
   color: "rgba(255, 255, 255, 0.8)",
   margin: "0",
   fontWeight: 500,
  },
  outgoingCallStatus: {
   textAlign: "center",
   color: "white",
  },
  outgoingCallStatusImg: {
   width: "120px",
   height: "120px",
   borderRadius: "50%",
   border: "3px solid rgba(255, 255, 255, 0.3)",
   marginBottom: "24px",
   objectFit: "cover",
  },
  outgoingCallStatusH3: {
   fontSize: "24px",
   fontWeight: 600,
   marginBottom: "8px",
  },
  outgoingCallStatusP: {
   fontSize: "16px",
   opacity: 0.9,
   margin: "0",
  },
  modernScreenshareOverlay: {
   position: "fixed",
   top: "0",
   left: "0",
   right: "0",
   bottom: "0",
   background: "#000",
   zIndex: 9999,
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   animationName: modernCallFadeIn,
   animationDuration: "0.4s",
   animationTimingFunction: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
  },
  modernScreenshareActive: {
   width: "100%",
   height: "100%",
   position: "relative",
   display: "flex",
   flexDirection: "column",
   background: "#0a0a0a",
   overflow: "hidden",
  },
  modernScreenshareHeader: {
   position: "absolute",
   top: "0",
   left: "0",
   right: "0",
   padding: "24px 32px",
   background:
    "linear-gradient(180deg, rgba(0, 0, 0, 0.9) 0%, rgba(0, 0, 0, 0) 100%)",
   display: "flex",
   alignItems: "center",
   justifyContent: "space-between",
   zIndex: 100,
   animationName: slideDownFade,
   animationDuration: "0.4s",
   animationTimingFunction: "ease",
   "@media (max-width: 768px)": {
    padding: "20px 16px",
   },
  },
  modernScreenshareInfo: {
   display: "flex",
   alignItems: "center",
   gap: "16px",
  },
  modernScreenshareIcon: {
   width: "48px",
   height: "48px",
   borderRadius: "50%",
   background: "rgba(255, 152, 0, 0.2)",
   border: "2px solid rgba(255, 152, 0, 0.4)",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   color: "#ff9800",
   fontSize: "20px",
   "@media (max-width: 768px)": {
    width: "40px",
    height: "40px",
    fontSize: "18px",
   },
  },
  modernScreenshareUserH3: {
   fontSize: "18px",
   fontWeight: 600,
   color: "white",
   margin: "0 0 4px 0",
   textShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
   "@media (max-width: 768px)": {
    fontSize: "16px",
   },
  },
  modernScreenshareUserP: {
   fontSize: "14px",
   color: "rgba(255, 255, 255, 0.8)",
   margin: "0",
   textShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
   "@media (max-width: 768px)": {
    fontSize: "13px",
   },
  },
  modernScreenshareMinimizeBtn: {
   width: "44px",
   height: "44px",
   borderRadius: "50%",
   border: "none",
   background: "rgba(255, 255, 255, 0.15)",
   backdropFilter: "blur(10px)",
   color: "white",
   fontSize: "16px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   transition: "all 0.2s ease",
   "@media (max-width: 768px)": {
    width: "40px",
    height: "40px",
    fontSize: "14px",
   },
  },
  modernScreenshareMinimizeBtnHover: {
   ":hover": {
    background: "rgba(255, 255, 255, 0.25)",
    transform: "scale(1.1)",
   },
  },
  modernScreenshareMinimizeBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernScreenshareContainer: {
   width: "100%",
   height: "100%",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   background: "#000",
   padding: "20px",
   boxSizing: "border-box",
   "@media (max-width: 768px)": {
    padding: "12px",
   },
  },
  modernScreenshareVideo: {
   maxWidth: "100%",
   maxHeight: "100%",
   width: "auto",
   height: "auto",
   objectFit: "contain",
   background: "#000",
   borderRadius: "8px",
   boxShadow: "0 8px 32px rgba(0, 0, 0, 0.5)",
  },
  modernScreenshareControlsWrapper: {
   position: "absolute",
   bottom: "0",
   left: "0",
   right: "0",
   padding: "32px",
   background:
    "linear-gradient(0deg, rgba(0, 0, 0, 0.9) 0%, rgba(0, 0, 0, 0) 100%)",
   display: "flex",
   justifyContent: "center",
   zIndex: 100,
   opacity: 0,
   transform: "translateY(20px)",
   transition: "all 0.3s ease",
   pointerEvents: "none",
   "@media (max-width: 768px)": {
    padding: "24px 16px",
    opacity: 1,
    transform: "translateY(0)",
    pointerEvents: "all",
   },
  },
  modernScreenshareControlsWrapperVisible: {
   opacity: 1,
   transform: "translateY(0)",
   pointerEvents: "all",
  },
  modernScreenshareControls: {
   display: "flex",
   gap: "20px",
   alignItems: "center",
  },
  modernScreenshareEndBtn: {
   width: "64px",
   height: "64px",
   borderRadius: "50%",
   border: "none",
   background: "#ff4757",
   color: "white",
   fontSize: "24px",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   transition: "all 0.2s ease",
   boxShadow: "0 4px 16px rgba(255, 71, 87, 0.4)",
   "@media (max-width: 768px)": {
    width: "60px",
    height: "60px",
    fontSize: "22px",
   },
  },
  modernScreenshareEndBtnHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.1)",
    boxShadow: "0 6px 24px rgba(255, 71, 87, 0.6)",
   },
  },
  modernScreenshareEndBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernMinimizedCall: {
   position: "fixed",
   width: "380px",
   background: "linear-gradient(135deg, #1a1a1a 0%, #0a0a0a 100%)",
   borderRadius: "20px",
   boxShadow:
    "0 16px 48px rgba(0, 0, 0, 0.8), 0 0 0 1px rgba(255, 255, 255, 0.1)",
   zIndex: 9999,
   overflow: "hidden",
   transition: "transform 0.2s ease, box-shadow 0.2s ease",
   userSelect: "none",
   WebkitUserSelect: "none",
   backdropFilter: "blur(20px)",
   "@media (max-width: 768px)": {
    width: "200px",
    borderRadius: "12px",
    cursor: "pointer",
   },
  },
  modernMinimizedScreenshare: {
   position: "fixed",
   width: "380px",
   background: "linear-gradient(135deg, #1a1a1a 0%, #0a0a0a 100%)",
   borderRadius: "20px",
   boxShadow:
    "0 16px 48px rgba(0, 0, 0, 0.8), 0 0 0 1px rgba(255, 255, 255, 0.1)",
   zIndex: 9999,
   overflow: "hidden",
   transition: "transform 0.2s ease, box-shadow 0.2s ease",
   userSelect: "none",
   WebkitUserSelect: "none",
   backdropFilter: "blur(20px)",
   "@media (max-width: 768px)": {
    width: "200px",
    borderRadius: "12px",
    cursor: "pointer",
   },
  },
  modernMinimizedCallHover: {
   ":hover": {
    boxShadow:
     "0 20px 60px rgba(0, 0, 0, 0.9), 0 0 0 1px rgba(255, 255, 255, 0.2)",
   },
  },
  modernMinimizedScreenshareHover: {
   ":hover": {
    boxShadow:
     "0 20px 60px rgba(0, 0, 0, 0.9), 0 0 0 1px rgba(255, 255, 255, 0.2)",
   },
  },
  modernMinimizedCallActive: {
   ":active": {
    transform: "scale(0.98)",
   },
  },
  modernMinimizedScreenshareActive: {
   ":active": {
    transform: "scale(0.98)",
   },
  },
  modernMinimizedHeader: {
   padding: "16px 20px",
   background: "rgba(0, 0, 0, 0.3)",
   borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
   "@media (max-width: 768px)": {
    padding: "8px 10px",
   },
  },
  modernMinimizedInfo: {
   display: "flex",
   alignItems: "center",
   gap: "12px",
  },
  modernMinimizedAvatar: {
   width: "44px",
   height: "44px",
   borderRadius: "50%",
   border: "2px solid rgba(255, 152, 0, 0.5)",
   objectFit: "cover",
   flexShrink: "0",
   "@media (max-width: 768px)": {
    width: "32px",
    height: "32px",
    fontSize: "14px",
   },
  },
  modernMinimizedScreenshareIcon: {
   width: "44px",
   height: "44px",
   borderRadius: "50%",
   background: "rgba(255, 152, 0, 0.15)",
   border: "2px solid rgba(255, 152, 0, 0.5)",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   color: "#ff9800",
   fontSize: "18px",
   flexShrink: "0",
   "@media (max-width: 768px)": {
    width: "32px",
    height: "32px",
    fontSize: "14px",
   },
  },
  modernMinimizedUser: {
   flex: "1",
   minWidth: "0",
  },
  modernMinimizedUserH4: {
   fontSize: "15px",
   fontWeight: 600,
   color: "white",
   margin: "0 0 4px 0",
   whiteSpace: "nowrap",
   overflow: "hidden",
   textOverflow: "ellipsis",
   "@media (max-width: 768px)": {
    fontSize: "12px",
   },
  },
  modernMinimizedUserP: {
   fontSize: "12px",
   color: "rgba(255, 255, 255, 0.6)",
   margin: "0",
   whiteSpace: "nowrap",
   overflow: "hidden",
   textOverflow: "ellipsis",
   "@media (max-width: 768px)": {
    fontSize: "10px",
   },
  },
  modernMinimizedVideo: {
   width: "100%",
   height: "200px",
   background: "#000",
   position: "relative",
   overflow: "hidden",
   "@media (max-width: 768px)": {
    height: "110px",
   },
  },
  modernMinimizedRemoteVideo: {
   width: "100%",
   height: "100%",
   objectFit: "cover",
  },
  modernMinimizedAudio: {
   width: "100%",
   height: "200px",
   background: "linear-gradient(135deg, #1a1a1a 0%, #0d0d0d 100%)",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   overflow: "hidden",
   "@media (max-width: 768px)": {
    height: "110px",
   },
  },
  modernMinimizedAudioWave: {
   width: "100px",
   height: "4px",
   background: "rgba(255, 152, 0, 0.3)",
   borderRadius: "2px",
   position: "relative",
   overflow: "hidden",
   "@media (max-width: 768px)": {
    width: "60px",
    height: "2px",
   },
  },
  modernMinimizedAudioWaveBefore: {
   "::before": {
    content: "\"\"",
    position: "absolute",
    top: "0",
    left: "0",
    width: "50%",
    height: "100%",
    background: "linear-gradient(90deg, transparent, #ff9800, transparent)",
    animationName: audioWave,
    animationDuration: "1.5s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
   },
  },
  modernMinimizedScreensharePreview: {
   width: "100%",
   height: "200px",
   background: "#000",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   overflow: "hidden",
   "@media (max-width: 768px)": {
    height: "110px",
   },
  },
  modernMinimizedScreenshareVideo: {
   width: "100%",
   height: "100%",
   objectFit: "contain",
   background: "#000",
  },
  modernMinimizedControls: {
   padding: "14px 20px",
   display: "flex",
   gap: "10px",
   justifyContent: "flex-end",
   background: "rgba(0, 0, 0, 0.3)",
   borderTop: "1px solid rgba(255, 255, 255, 0.05)",
   "@media (max-width: 768px)": {
    display: "none",
   },
  },
  modernMinimizedBtn: {
   width: "40px",
   height: "40px",
   borderRadius: "50%",
   border: "none",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   fontSize: "14px",
   transition: "all 0.2s ease",
   flexShrink: "0",
  },
  modernMinimizedMaximize: {
   background: "rgba(255, 255, 255, 0.1)",
   color: "white",
  },
  modernMinimizedMaximizeHover: {
   ":hover": {
    background: "rgba(255, 255, 255, 0.2)",
    transform: "scale(1.1)",
   },
  },
  modernMinimizedEnd: {
   background: "#ff4757",
   color: "white",
  },
  modernMinimizedEndHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.1)",
   },
  },
  modernMinimizedEndI: {
   transform: "rotate(135deg)",
  },
  modernMinimizedBtnActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  modernMinimizedCallAll: {
   pointerEvents: "none",
  },
  modernMinimizedScreenshareAll: {
   pointerEvents: "none",
  },
  modernMinimizedCallButton: {
   pointerEvents: "all",
  },
  modernMinimizedScreenshareButton: {
   pointerEvents: "all",
  },
  modernCallUser: {},
  modernMuteBtn: {},
  modernCameraBtn: {},
  muted: {},
  cameraOff: {},
  incomingCallNotification: {
   position: "fixed",
   top: "20px",
   right: "20px",
   background: "var(--bg-secondary)",
   border: "2px solid var(--button-primary)",
   borderRadius: "12px",
   boxShadow: "0 8px 32px var(--shadow)",
   zIndex: 1000,
   minWidth: "320px",
   animationName: slideInFromRight,
   animationDuration: "0.3s",
   animationTimingFunction: "ease-out",
   "@media (max-width: 768px)": {
    top: "10px",
    left: "10px",
    right: "10px",
    minWidth: "unset",
   },
  },
  incomingCallContent: {
   padding: "16px",
   display: "flex",
   alignItems: "center",
   justifyContent: "space-between",
   gap: "12px",
  },
  incomingCallInfo: {
   display: "flex",
   alignItems: "center",
   gap: "12px",
   flex: "1",
  },
  incomingCallAvatar: {
   width: "48px",
   height: "48px",
   borderRadius: "50%",
   objectFit: "cover",
   border: "2px solid var(--border)",
  },
  incomingCallText: {
   display: "flex",
   flexDirection: "column",
   minWidth: "0",
  },
  incomingCallTextH4: {
   margin: "0",
   fontSize: "16px",
   fontWeight: 600,
   color: "var(--text-primary)",
  },
  incomingCallTextP: {
   margin: "2px 0 0 0",
   fontSize: "14px",
   color: "var(--text-secondary)",
  },
  incomingCallActions: {
   display: "flex",
   gap: "8px",
   alignItems: "center",
  },
  btnSmallActive: {
   ":active": {
    transform: "scale(0.95)",
   },
  },
  declineBtnSmall: {
   width: "40px",
   height: "40px",
   border: "none",
   borderRadius: "50%",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   transition: "all 0.2s ease",
   background: "#ff4757",
   color: "white",
   flexShrink: "0",
  },
  declineBtnSmallHover: {
   ":hover": {
    background: "#ff3838",
    transform: "scale(1.08)",
   },
  },
  acceptBtnSmall: {
   width: "40px",
   height: "40px",
   border: "none",
   borderRadius: "50%",
   cursor: "pointer",
   display: "flex",
   alignItems: "center",
   justifyContent: "center",
   position: "relative",
   transition: "all 0.2s ease",
   background: "#2ed573",
   color: "white",
   flexShrink: "0",
  },
  acceptBtnSmallHover: {
   ":hover": {
    background: "#26d063",
    transform: "scale(1.08)",
   },
  },
 }
);
