import * as stylex from '@stylexjs/stylex';

const fadeIn = stylex.keyframes({
 from: { opacity: 0 },
 to: { opacity: 1 },
});

const slideIn = stylex.keyframes({
 from: { opacity: 0, transform: 'translateY(-20px) scale(0.95)' },
 to: { opacity: 1, transform: 'translateY(0) scale(1)' },
});

export const LinkWarningModalStyles = stylex.create({
 overlay: {
  position: 'fixed',
  inset: 0,
  zIndex: 99999,
  backgroundColor: 'rgba(0,0,0,0.6)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  animationName: fadeIn,
  animationDuration: '0.2s',
  animationTimingFunction: 'ease-out',
  animationFillMode: 'forwards',
 },
 modal: {
  backgroundColor: 'var(--bg-primary)',
  borderRadius: '16px',
  padding: '24px',
  maxWidth: '420px',
  width: '90%',
  boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: 'var(--border)',
  animationName: slideIn,
  animationDuration: '0.25s',
  animationTimingFunction: 'ease-out',
  animationFillMode: 'forwards',
 },
 icon: {
  fontSize: '32px',
  textAlign: 'center',
  marginBottom: '12px',
  display: 'block',
  color: '#f59e0b',
 },
 title: {
  marginTop: 0,
  marginBottom: '8px',
  textAlign: 'center',
  color: 'var(--text-primary)',
  fontSize: '18px',
  fontWeight: '700',
 },
 description: {
  color: 'var(--text-secondary)',
  textAlign: 'center',
  marginTop: 0,
  marginBottom: '16px',
  fontSize: '14px',
  lineHeight: '1.5',
 },
 urlBox: {
  backgroundColor: 'var(--bg-tertiary)',
  borderRadius: '8px',
  paddingTop: '10px',
  paddingBottom: '10px',
  paddingLeft: '14px',
  paddingRight: '14px',
  marginBottom: '20px',
  wordBreak: 'break-all',
  fontSize: '13px',
  color: 'var(--text-secondary)',
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: 'var(--border)',
 },
 buttons: {
  display: 'flex',
  gap: '10px',
 },
 cancelBtn: {
  flex: '1',
  paddingTop: '10px',
  paddingBottom: '10px',
  paddingLeft: '16px',
  paddingRight: '16px',
  borderRadius: '8px',
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: 'var(--border)',
  backgroundColor: 'var(--bg-secondary)',
  color: 'var(--text-primary)',
  cursor: 'pointer',
  fontWeight: '600',
  fontSize: '14px',
  transitionProperty: 'all',
  transitionDuration: '0.2s',
  ':hover': {
   backgroundColor: 'var(--border)',
  },
 },
 visitBtn: {
  flex: '1',
  paddingTop: '10px',
  paddingBottom: '10px',
  paddingLeft: '16px',
  paddingRight: '16px',
  borderRadius: '8px',
  borderWidth: 0,
  borderStyle: 'solid',
  backgroundColor: '#ff4757',
  color: '#fff',
  cursor: 'pointer',
  fontWeight: '600',
  fontSize: '14px',
  transitionProperty: 'all',
  transitionDuration: '0.2s',
  ':hover': {
   backgroundColor: '#e0323f',
  },
 },
});